requires 'Minion';
requires 'Mojolicious::Plugin::XslateRenderer';
requires 'Mojolicious::Plugin::RenderFile';
requires 'Mojo::Pg';
requires 'DateTime::Format::Pg';

test_requires "Test::More";
test_requires "Test::Deep";
