#!/usr/bin/env perl
use strict;
use warnings;

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

# Start command line interface for application, use CGI mode if no arguments.
Mojolicious::Commands->start_app('MarkdownSite::CGI', (@ARGV ? () : 'cgi') );
