#!/usr/bin/env perl
use warnings;
use strict;
use Cache::Memcached::Fast;
use Data::Dumper;

my $domain = shift @ARGV;

die "Require domain name as argument" unless $domain;

my $mem = Cache::Memcached::Fast->new({
    servers   => [ { address => '127.0.0.1:11211' } ],
    namespace => "$domain/",
});

my $routes = $mem->get( 'routes' );

print Dumper $routes;
